[package]
name = "my-geometry"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10.1", features = ["dynamic_linking"] }
bevy_prototype_lyon = "0.8.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = "thin"
